### ISSUE TITLE
England is not a country

### ISSUE THREAD

**Issue by dextermb** [DivineOmega/php-countries#3]
I can't seem to find a country called "England" by name! 😨

**Comment by Jord-JD** [comment]
The current data source provides countries as defined by the [ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) standard, which does not define England as a country.

We would need to implement to ISO 3166-2 standards to support England, specifically ISO [3166-2:GB](https://en.wikipedia.org/wiki/ISO_3166-2:GB).

**Comment by Jord-JD** [comment]
I'm open to PRs that provide a new or extended data source that supports ISO 3166-2.
